source 'https://rubygems.org'
gem 'sinatra'
gem 'rackup'
gem 'puma'
gem 'haml'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'taglib-ruby'
gem 'ruby-vips'
gem 'serialport'

#development
gem 'pry'

gem "rqrcode", "~> 3.1"
